---
 - name: Kopiere Chunkserverkonfig
   template: src={{ item }}.j2 dest=/etc/mfs/{{ item }} owner=root group=root mode=0644
   with_items:
     - mfschunkserver.cfg
     - mfshdd.cfg
   notify: reload lizardfs-chunkserver
   
 - name: Setze Berechtigungen mfshdd Verzeichnisse
   file: path={{ item.mountpoint }} owner=mfs group=mfs mode=0755
   with_items: "{{ lizardfs.disks }}"

 - name: Installiere lizardfs-chunkserver
   apt: name=lizardfs-chunkserver state=present

 - name: Aktiviere lizardfs-chunkserver als Service
   template: src=lizardfs-chunkserver.j2 dest=/etc/default/lizardfs-chunkserver mode=0644 force=yes

